<?php

namespace App\Models;

use App\Models\Concerns\HasUuid;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Shared base for AUTOSECURE domain models.
 *
 * Every model that extends this has `id`, `uuid`, uuid route binding and is
 * factory-enabled.
 */
abstract class BaseModel extends Model
{
    use HasFactory;
    use HasUuid;

    /**
     * The id and uuid are never mass assignable; uuid is generated by the model
     * and the id is assigned by the database.
     */
    protected $guarded = ['id', 'uuid'];
}
